tap "candid82/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "yqrashawn/goku"

# TODO: Not sure if these are required
# brew "bash-completion"
# brew "openssl@1.1"
# brew "readline"
# brew "xz"
# brew "poppler"
# brew "zlib"

brew "fzf"
brew "git"
brew "neovim"
brew "node"
brew "pgcli"
brew "prettier"
brew "pyenv"
brew "stow"
brew "tmux"
brew "zplug"
brew "yqrashawn/goku/goku"

cask "inkscape"
