tap "candid82/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "yqrashawn/goku"

# Python build dependencies
brew "openssl@1.1"
brew "readline"
brew "sqlite3"
brew "xz"
brew "zlib"

brew "bash-completion"
brew "fzf"
brew "git"
brew "gh"
brew "neovim"
brew "node"
brew "pgcli"
brew "prettier"
brew "pyenv"
brew "stow"
brew "tmux"
brew "zplug"
brew "yqrashawn/goku/goku"
